#!/bin/bash
#SBATCH --nodes=1
#SBATCH --partition=batch
#SBATCH -J excomp
#SBATCH -o excomp.%J.out
#SBATCH -e excomp.%J.err
#SBATCH --mail-type=ALL
#SBATCH --time=20:00
#SBATCH --mem=10G


#run the application:
module load R/3.6.0/gnu-6.4.0
Rscript extractAR12modes.R $1  
