#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=3
#SBATCH --cpus-per-task=10
#SBATCH --partition=batch
#SBATCH -J simuljobrAR2
#SBATCH -o simuljobRAR2.%J.out
#SBATCH -e simuljobRAR2.%J.err
#SBATCH --mail-type=ALL
#SBATCH --time=01:30:00
#SBATCH --mem=8G

#run the application:
module load R/3.6.0/gnu-6.4.0
Rscript simulationmixAR2.R $1  
