#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=3
#SBATCH --cpus-per-task=10
#SBATCH --partition=batch
#SBATCH -J simuljobrMA4
#SBATCH -o simuljobMA4.%J.out
#SBATCH -e simuljobMA4.%J.err
#SBATCH --mail-type=ALL
#SBATCH --time=2:40:00
#SBATCH --mem=8G

#run the application:
module load R/3.6.0/gnu-6.4.0
Rscript simulationMA4.R $1  
