#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=3
#SBATCH --cpus-per-task=10
#SBATCH --partition=batch
#SBATCH -J choudhuri
#SBATCH -o choud.%J.out
#SBATCH -e choud.%J.err
#SBATCH --mail-type=ALL
#SBATCH --time=29:00:00

#run the application:
module load R/3.6.0/gnu-6.4.0
Rscript chouduripgramcode.R $1  
